### ISSUE TITLE
타 자료와 충돌이 발생하네요.

### ISSUE THREAD

**Issue by wookho** [probi/Ding_Fixed_Banner#2]
http://webconsoft.co.kr/webcon_p_widgets/936

위 자료의 뉴스가 출력이 되지 않네요.

**Comment by probi** [comment]
1.3 Version 확인 부탁드립니다.

**Comment by wookho** [comment]
@probi 

동일하게 뉴스 출력이 안됩니다. 
Uncaught TypeError: Cannot read property 'ajax' of undefineddognews:1031 (anonymous function)jquery.min.js:2 f.Callbacks.ojquery.min.js:2 f.Callbacks.p.fireWithjquery.min.js:2 e.extend.readyjquery.min.js:2 c.addEventListener.B

**Comment by wookho** [comment]
1.3버전 적용후 추가로 발생하는 문제가 배너가 위로 설정했는데 아래에 뜹니다.
1.2버전으로 다시 설치했어요.

**Comment by probi** [comment]
위로 설정하였을 때, 아래로 출력되던 점 수정하였습니다.
충돌 문제 관련으로는 여러 환경을 구성 해놓고 테스트를 해볼 생각입니다.

**Comment by wookho** [comment]
@probi 해당자료가 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script> 를 사용하는데 저희는 레이아웃에 추가하면 다른 자료들과 문제가 생겨 해당 위젯의 스킨에 위 스크립트를 적용하여 사용중입니다. 저 스크립트가 동작하지 않으면 뉴스가 출력되지 않아요.

**Comment by probi** [comment]
http://code.jquery.com/jquery-2.1.3.min.js 
이 스크립트를 로드 시켜주세요.

**Comment by wookho** [comment]
@probi 스크립트를 교체 했는데요. 배너애드온을 해당페이지에 활성화 하면 뉴스가 마찬가지로 출력이 되지 않아요.

**Comment by probi** [comment]
웹콘 네이버 뉴스검색 위젯 다운로드가 안되네요.
pro_bi@naver.com으로 파일을 보내주실 수 있으신가요?

**Comment by wookho** [comment]
@probi 보내드렸습니다.

**Comment by probi** [comment]
보내주신 자료를 확인 했습니다만, 보내주신 뉴스 위젯과는 충돌이 없습니다.
아래 저희 딩의 공식 페이스북에 방문 하셔서 메시지를 남겨주세요. 한 가지 걸리는 문제가 있는데 
실시간으로 대화 해야할 것 같습니다.
https://www.facebook.com/pages/%EB%94%A9-Ding/554701971272023

**Comment by wookho** [comment]
@probi 저희는 해당자료와 충돌문제 크게 문제될 것은 없어요.

**Comment by probi** [comment]
{@ 
	$unique = rand(0,100);
	$s_title = $widget_info->search_title;
    $list_count = $widget_info->rows_list_count*$widget_info->page_count;
    $str_cutsize = $widget_info->subject_cut_size;
    $dispaly_list = $widget_info->rows_list_count;
}
<div class="N_contents_container_{$unique}">
	
		<div class="header_title" style="padding:5px;"></div>
    
	<ul id="list"></ul>    
    
    	<ul class="list_navi">
        	<li><a onclick="N_content_prev(jQuery(this).parents('.N_contents_container_{$unique} ul.list_navi').prev('.N_contents_container_{$unique} ul.#list'),{$widget_info->rows_list_count});">이전</a></li>
            <li><a onclick="N_content_next(jQuery(this).parents('.N_contents_container_{$unique} ul.list_navi').prev('.N_contents_container_{$unique} ul.#list'),{$widget_info->rows_list_count});">다음</a></li>
        </ul>
    
</div>
<script type="text/javascript">
var ran = Math.floor(Math.random()*45);

(function ($){
    $(document).ready(function () {
        var query_data =  encodeURIComponent("{$s_title}");
        var listCount = Number("{$list_count}");
        var display_list = Number("{$dispaly_list}");
        var str_cutsize = Number("{$str_cutsize}");
        $.ajax({
            url : 'widgets/webcon_N_newsSearch/skins/N_newsSearch/dataProxy.php',
            dataType : 'json' ,
            type : 'POST' ,
            data:{
                "query":query_data
            },
            success:function(data){
                if(data['channel']['item'].length > 0){
                    var start =0 ;
                    content_li = "<div style='font-size:14px;'>"+ data['channel'].description +"</div>";
                    $('.N_contents_container_{$unique} > .header_title').append(content_li);
                    for(var i in data['channel']['item']){
                        if(start < listCount){
                            var item = data['channel']['item'][i];
                            if(start >= display_list){
                                var content_li = "<li style='display:none;'>";
                            }else{
                                var content_li = "<li>";
                            }
                            content_li += "<p class='title'><a href='"+ item.link +"' target='_black'> - " + cutStr(item.title,str_cutsize) +"</a>";
                            content_li += "<font style='color:#788eb7; font-size:10px;'>&nbsp;("+item.author+")</font>";
                            content_li += "</p>";
                            content_li += "</li>";
                            $('.N_contents_container_{$unique} > #list').append(content_li);
                        }
                        start++;
                    }
                }else{
                    var content_li = "<li style='text-align:center;'>※ 검색데이터 목록이 없습니다.</li>";
                    $('.N_contents_container_{$unique} > #list').append(content_li);
                }
            },error:function(e){}
        });
    });

})(jQuery.noConflict());


 
function N_content_next(obj,list_per_page){
	if(obj.is('ul')) {
		var list = jQuery('>li',obj);
	}
	var total_page = parseInt((list.size()-1) / list_per_page,10)+1;
	list.each(function(i){
		if(jQuery(this).css('display') !='none'){
			page = parseInt(i/list_per_page,10) + 1;
			return false;
		}
	});
	if(total_page <= page) return;
	list.each(function(i){
		if( (page* list_per_page) <= i && ((page+1) * list_per_page) > i){
			jQuery(this).show();
		}else{
			jQuery(this).hide();
		}
	});
}

function N_content_prev(obj,list_per_page){
	if(obj.is('ul')){
		var list = jQuery('>li',obj);
	}
	var total_page = parseInt((list.size()-1) / list_per_page,10)+1;
	list.each(function(i){
		if(jQuery(this).css('display') !='none'){
			page = parseInt(i/list_per_page,10)+1;
			return false;
		}
	});
	if(page <= 1) return;
	list.each(function(i){
		if( ((page-2)* list_per_page)<= i && ((page-1) * list_per_page) > i){
			jQuery(this).show();
		}else{
			jQuery(this).hide();
		}
	});
}
function cutStr(str,limit){
	  var tmpStr = str;
	  var byte_count = 0;
	  var len = str.length;
	  var dot = "";
	  
	  for(i=0; i<len; i++){
			byte_count += chr_byte(str.charAt(i)); 
			if(byte_count == limit-1){
				if(chr_byte(str.charAt(i+1)) == 2){
					tmpStr = str.substring(0,i+1);
					dot = "...";
				}else {
			if(i+2 != len) dot = "...";
				tmpStr = str.substring(0,i+2);
			 }
			 break;
			}else if(byte_count == limit){
				if(i+1 != len) dot = "...";
				tmpStr = str.substring(0,i+1);
				break;
			}
	  }
	  return tmpStr+dot;
}
function chr_byte(chr){
  if(escape(chr).length > 4)
    return 2;
  else
    return 1;
}
</script>

이렇게 수정해주었더니, 충돌나지 않네요.

**Comment by probi** [comment]
(function ($){
$(document).ready(function () {
        var query_data =  encodeURIComponent("{$s_title}");
        var listCount = Number("{$list_count}");
        var display_list = Number("{$dispaly_list}");
        var str_cutsize = Number("{$str_cutsize}");
...
})(jQuery.noConflict());

이렇게 수정해주면 에러가 안나는데 혹시 다른 콘텐츠하고 오류가 발생하나요 ?
http://dingsoft.kr/xe/index.php?mid=page_JNty56
저희 테스트 페이지 입니다.

**Comment by wookho** [comment]
@probi 어디를 수정하라는 것이지 명확하지 않아 제가 수정을 못해보겠네요.

**Comment by probi** [comment]
메일로 변경된 list.html 보내드리도록 하겠습니다.

**Comment by wookho** [comment]
감사합니다. 보내주신자료로 하니 잘 되네요.
