### ISSUE TITLE
1.3.1 배너 위치 오류

### ISSUE THREAD

**Issue by wookho** [probi/Ding_Fixed_Banner#3]
배너의 위치가 잘못 잡힙니다. 사이트의 상단 일부를 가려버리네요.

![banner](https://cloud.githubusercontent.com/assets/6590236/7131411/0247f4c0-e2ba-11e4-8e1b-40e4150587a2.png)

**Comment by probi** [comment]
잘못 수정한 부분이 있었네요, 수정 하도록 하겠습니다. 감사합니다!

**Comment by probi** [comment]
@wookho
Github에서 다운로드 하시면 1.3.2로 패치된 자료로 다운로드 가능 하십니다.  감사합니다. ^^
